.TH ServizioPubblico 1
.SH NAME
.B serviziopubblico
- Un semplice script per scaricare le puntate di Servizio Pubblico

.SH DESCRIPTION
Un semplice script che permette la visione di 
.B Servizio Pubblico
senza l'utilizzo di un browser dedicato.

Lo stream è trasmesso all'indirizzo:
.I http://www.serviziopubblico.it/

.SH OPTIONS
.IP -d
download video
.IP -u
show the http file url
.IP "-p player"
usa il
.I player
preferito, default è
.IR vlc

.SH AUTHOR
Leo Iannacone <l3on@ubuntu.com>

.SH COPYRIGHT
Copyright   ©   2014   Leo Iannacone
    http://leoiannacone.com

License   GPLv3+:   GNU  GPL  version  3  or  later
   <http://gnu.org/licenses/gpl.html>.
