#!/usr/bin/python

from subprocess import call
from re import findall
from optparse import OptionParser
from urllib2 import urlopen

HOST = "serviziopubblico.it"

class ServizioPubblico():

    def __init__(self, url):

        data = urlopen(url).read()

        self.title = findall('entry-title.*>(.*)<', data)[0]
        self.id = findall('data-embed="([0-9]+)"', data)[0]

        info_base= "http://mediasp.meride.tv/embedproxy.php/sp/folder1/%s/" % self.id
        data = urlopen(info_base).read()

        self.url = findall('<mp4><!\[CDATA\[(.*)\]\]></mp4>', data)[0]

        self.quality = findall('<iphone><!\[CDATA\[.*sp,(.*),.*\]\]></iphone>', data)[0]
        self.quality = [int(i) for i in self.quality.split(',')]
        self.quality.sort()

        # set best quality
        old_quality = findall('_sp(.*).mp4', self.url)[0]
        self.url_best_quality = self.url.replace('_sp%s' % old_quality, '_sp%s' % self.quality[-1])

def main():
    usage = 'usage: %prog [options] url'
    parser = OptionParser(usage)
    parser.add_option('-d', '--download', action="store_true", default=False, help='download video')
    parser.add_option('-p', '--player', default="vlc", help='choose video player [default: %default]')

    opts, args = parser.parse_args()

    if len(args) is 0 or args[0].find(HOST) < 0:
        print('Please provide a valid url for %s' % HOST)
        parser.print_usage()
        exit(1)

    page = args[0]
    provider = ServizioPubblico(page)

    url = provider.url_best_quality
    title = provider.title

    if opts.download:
        call("wget -c %s -O '%s.mp4'" % (url, title.replace(' ','_')),
            shell = True
            )
    else:
        call("%s %s" % (opts.player, url), 
            shell = True
            )

if __name__ == '__main__':
    main()

